# DecapBridge PKCE authentication
backend:
  name: git-gateway
  repo: filycuellar/prueba_maribel
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/d55b5f7b-3e50-4b20-8f44-110a0628f46e/pkce
  auth_token_endpoint: /sites/d55b5f7b-3e50-4b20-8f44-110a0628f46e/token
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

locale: es
site_url: https://filycuellar.github.io/prueba_maribel/
display_url: https://filycuellar.github.io/prueba_maribel/
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

media_folder: "assets/blog"
public_folder: "/prueba_maribel/assets/blog"

publish_mode: simple

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Artículo"
    folder: "_posts"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{date}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - label: "Categoría"
        name: "category"
        widget: "select"
        options:
          - "Literatura"
          - "Poesía"
          - "Educación"
          - "Cultura"
          - "Paz"
          - "Escritura"
          - "Noticias"
      - { label: "Imagen principal", name: "image", widget: "image", required: false }
      - { label: "Resumen", name: "excerpt", widget: "text", hint: "Texto breve que aparecerá en la página principal del Blog." }
      - { label: "Contenido", name: "body", widget: "markdown" }
